export default (data) => {
  return [
    'amphibian',
    'amphiuma',
    'army of frogs',
    'barking frog',
    'black toad',
    'brook salamander',
    'bullfrog',
    'caecilian',
    'clawed frog',
    'climbing salamander',
    'common frog',
    'crested newt',
    'cricket frog',
    'disc tongued frog',
    'dusky salamander',
    'dwarf siren',
    'eastern newt',
    'ensatina',
    'uropean toad',
    'fire belly newt',
    'fire salamander',
    'fork tongued frog',
    'frog',
    'froglet',
    'errothorax',
    'ghost frog',
    'giant salamander',
    'glass frog',
    'oliath frog',
    'gold frog',
    'ground frog',
    'hellbender',
    'horned frog',
    'ndonesian floating frog',
    'efferson salamander',
    'knobby newt',
    'knot of toads',
    'leopard frog',
    'litter frog',
    'long toed salamander',
    'mantella frog',
    'exican treefrog',
    'moss frog',
    'mudpuppy',
    'mud salamander',
    'narrow mouthed frog',
    'natterjack',
    'newt',
    'ornate horned frog',
    'paddle tail newt',
    'painted frog',
    'poison arrow frog',
    'poison dart frog',
    'pollywog',
    'red legged frog',
    'red eft',
    'red eyed tree frog',
    'red salamander',
    'rice frog',
    'saddleback toad',
    'salamander',
    'sedge frog',
    'shovelnose frog',
    'siren',
    'spadefoot',
    'spotted newt',
    'spring peeper frog',
    'spring salamander',
    'tadpole',
    'tailed frog',
    'toad',
    'tongueless frog',
    'torrent salamander',
    'treefrog',
    'true frog',
    'true toad',
    'ietnamese tree frog',
    'warty newt',
    'waterdog',
    'water frog',
    'western toad',
    'wood frog',
    'woodlands salamander',
    'yellow legged frog'
  ].join('|');
}
