export default (data) => {
  return [
    'albedo',
    'lpha entauri',
    'apastron',
    'aperature',
    'aphelion',
    'apogee',
    'asterism',
    'asteroid',
    'astronaut',
    'astronomer',
    'astronomical unit',
    'astronomy',
    'axial tilt',
    'azimuth',
    'background radiation',
    'ailey\'s beads',
    'big bang theory',
    'binary star',
    'black body',
    'black hole',
    'bolometer',
    'celestial',
    'celestial equator',
    'cislunar',
    'cluster',
    'comet',
    'conjunction',
    'constellation',
    'coriolis force',
    'cosmic rays',
    'corona',
    'cosmology',
    'cosmonaut',
    'cosmos',
    'crater',
    'crescent moon',
    'dark matter',
    'declination',
    'deep space',
    'eneb',
    'density',
    'docking',
    'oppler shift',
    'double star',
    'rake equation',
    'dust',
    'dwarf planet',
    'dwarf star',
    'arth',
    'earthbound',
    'eccentricity',
    'eclipse',
    'ecliptic',
    'elliptical orbit',
    'equinox',
    'escape velocity',
    'event horizon',
    'exoplanet',
    'extragalaxtic',
    'falling star',
    'flare',
    'flyby',
    'free fall',
    'full moon',
    'galaxy',
    'gamma ray',
    'gas giant',
    'gegenschein',
    'geostationary',
    'geosynchronous',
    'gibbous moon',
    'globular cluster',
    'gravitation',
    'gravitational constant',
    'gravitational lens',
    'gravity',
    'half moon',
    'heliocentric',
    'hydrogen',
    'helium',
    'ubble telescope',
    'ubble\'s law',
    'hyperbolic orbit',
    'hypernova',
    'ice giant',
    'inclination',
    'inertia',
    'inferior planets',
    'inner planets',
    'interstellar',
    'interstellar dust',
    'ionosphere',
    'upiter',
    'epler\'s laws',
    'kiloparsec',
    'irkwood gaps',
    'uiper belt',
    'agrange points',
    'lens',
    'light-year',
    'local arm',
    'local group',
    'lunar',
    'magnitude',
    'mare',
    'ars',
    'mass',
    'ercury',
    'meteor',
    'meteor shower',
    'meteorite',
    'meteoroid',
    'ilky ay',
    'minor planet',
    'ir',
    'moon',
    'muttnik',
    'nadir',
    'nebula',
    'eptune',
    'neutron star',
    'new moon',
    'north star',
    'nova',
    'observatory',
    'occultation',
    'ort cloud',
    'opposition',
    'orbit',
    'orbital eccentricity',
    'orbital inclination',
    'outer planets',
    'parallax',
    'parsec',
    'partial eclipse',
    'penumbra',
    'perigee',
    'perihelion',
    'perturbation',
    'phase',
    'plane of the ecliptic',
    'planet',
    'planetary nebula',
    'planetoid',
    'luto',
    'pole star',
    'precession',
    'probe',
    'pulsar',
    'quarter moon',
    'quasar',
    'radiant',
    'radiation',
    'red dwarf',
    'red giant star',
    'red shift',
    'revolve',
    'right ascension',
    'rings',
    'oche limit',
    'rocket',
    'satellite',
    'aturn',
    'scientific notation',
    'scintillation',
    'shooting star',
    'solar',
    'sidereal',
    'singularity',
    'sky',
    'solar',
    'solar system',
    'solar wind',
    'solstice',
    'space',
    'space exploration',
    'space station',
    'spectroscope',
    'spectrum',
    'putnik',
    'star',
    'starlight',
    'sun',
    'sunspot',
    'superior planets',
    'supernova',
    'synodic',
    'syzygy',
    'telemetry',
    'telescope',
    'terminator',
    'terrestrial',
    'total eclipse',
    'totality',
    'transit',
    'translunar',
    'transneptunians',
    'twinkling',
    'umbra',
    'universe',
    'ranus',
    'vacuum',
    'an llen belt',
    'variable star',
    'enus',
    'vernal equinox',
    'visual magnitude',
    'waning',
    'wavelength',
    'waxing',
    'weightlessness',
    'white dwarf',
    'white giant',
    'wormhole',
    'x-rays',
    'yellow dwarf',
    'zenith',
    'zodiac'
  ].join('|');
}
