import pluralize from '../helpers/pluralize';

let words = [
  'antiseptic',
  'aspirin',
  'atomizer',
  'bandages',
  'basin',
  'bath',
  'bath mat',
  'bath robe',
  'bath towel',
  'bathtub',
  'bidet',
  'brush',
  'bubble bath',
  'bubbles',
  'cleaning',
  'cologne',
  'comb',
  'conditioner',
  'cotton balls',
  'curlers',
  'curling iron',
  'dental floss',
  'disinfectant',
  'droppers',
  'eau de cologne',
  'emery board',
  'eyedropper',
  'face cloth',
  'faucet',
  'floss',
  'flush',
  'garbage can',
  'hairbrush',
  'hair dryer',
  'hamper',
  'hand towel',
  'laundry hamper',
  'lavatory',
  'loofah',
  'lotion',
  'make up',
  'medications',
  'medicine',
  'medicine cabinet',
  'mirror',
  'moisturizer',
  'mouthwash',
  'nail clippers',
  'nail file',
  'nail polish',
  'nail scissors',
  'ointment',
  'paper towel',
  'perfume',
  'plumbing',
  'plunger',
  'powder',
  'Q tips',
  'razor',
  'razor blade',
  'restroom',
  'rug',
  'scale',
  'scissors',
  'shampoo',
  'shave',
  'shaver',
  'shaving cream',
  'shower',
  'shower curtain',
  'shower stall',
  'sink',
  'soap',
  'soap dish',
  'soap dispenser',
  'sponge',
  'swabs',
  'talcum power',
  'tissues',
  'toilet',
  'toilet paper',
  'toilet seat',
  'toothbrush',
  'toothpaste',
  'towel',
  'towel rack',
  'trash can',
  'tub',
  'tweezers',
  'urinal',
  'wash',
  'wash basin',
  'washroom',
  'waste basket',
  'water',
  'water closet',
  'WC',
  'whirlpool',
  'wipes'
];

export default (data) => {
  return pluralize(words);
}
