import pluralize from '../helpers/pluralize';

let words = [
  'abyssal',
  'Alpine',
  'aquatic',
  'Arctic',
  'bayou',
  'benthic zone',
  'biome',
  'bog',
  'boreal forest',
  'broadleaf forest',
  'campo',
  'cave',
  'chaparral',
  'city',
  'coastal river',
  'cold seep',
  'coniferous forest',
  'coral reef',
  'deciduous forest',
  'deep sea',
  'deep sea trench',
  'desert',
  'disphotic zone',
  'ecoregion',
  'ecosystem',
  'ecozone',
  'euphotic zone',
  'fen',
  'flooded grassland',
  'floodplain',
  'forest',
  'freshwater biomes',
  'freshwater marsh',
  'glade',
  'grasslands',
  'habitat',
  'hadal',
  'heath',
  'highland',
  'hydrothermal vent',
  'intertidal zone',
  'jungle',
  'kelp forest',
  'lacustrine',
  'land cave',
  'littoral zone',
  'mangrove forest',
  'marine biomes',
  'marsh',
  'marshland',
  'meadow',
  'Mediterranean forest',
  'Mediterranean scrub',
  'Mediterranean woodland',
  'mire',
  'mixed forest',
  'montane grassland',
  'moor',
  'neritic zone',
  'northern coniferous forest',
  'ocean open sea',
  'pack ice',
  'palustrine',
  'pampas',
  'peat bog',
  'peatland',
  'peat swamp',
  'pelagic zone',
  'playa',
  'polar',
  'polar desert',
  'pond',
  'prairie',
  'quagmire',
  'rainforest',
  'riparian zone',
  'river delta',
  'salt marsh',
  'savanna',
  'sclerophyll forest',
  'scrub',
  'sea cave',
  'sea trench',
  'shrubland',
  'slough',
  'steppe',
  'swamp',
  'taiga',
  'temperate deciduous forest',
  'temperate rainforest',
  'terrestrial biomes',
  'terrestrial cave',
  'tide pools',
  'tropical rainforest',
  'tundra',
  'upland river',
  'veldt',
  'wetland',
  'wet meadow',
  'woodland',
  'woods',
  'xeric shrubland'
];

export default (data) => {
  return pluralize(words);
}
