import pluralize from '../helpers/pluralize';

let words = [
  'absorption',
  'acceptance of a bill',
  'accommodation bill',
  'ad valorem',
  'adjustment entries',
  'affidavit',
  'agenda',
  'agreement',
  'allonge',
  'allotment',
  'amalgamation',
  'amazon',
  'annuity',
  'antidiscrimination',
  'assessment',
  'assets',
  'auditor',
  'authorized capital',
  'bad debts',
  'bailment',
  'balance sheet',
  'bank reconciliation statement',
  'banking',
  'barter',
  'based',
  'bill dishonoured',
  'bill maturity of a',
  'bill of exchange',
  'bill of lading',
  'bill of sight',
  'bills payable',
  'binational',
  'biz',
  'bonafide',
  'bond',
  'bonded goods',
  'bought',
  'breakage',
  'brokerage',
  'brought down',
  'brought forward',
  'bullish',
  'bureau of the census',
  'business',
  'business college',
  'business enterprise',
  'buy',
  'buyer',
  'c and f',
  'cif',
  'c.i.f',
  'cambial',
  'capital',
  'capitalists',
  'cargo',
  'carriage trade',
  'carried down',
  'carried forward',
  'cart',
  'cash against document',
  'cash discount',
  'cash on delivery',
  'cash transactions',
  'census bureau',
  'cheque, crossed',
  'cheque, post dated',
  'collateral security',
  'colony',
  'columnar system',
  'commerce department',
  'commerced',
  'commercial',
  'commercial document',
  'commercial enterprise',
  'commercial instrument',
  'commercial treaty',
  'commercialism',
  'commercialize',
  'commercing',
  'commodity',
  'company',
  'compound entry',
  'consignment invoice',
  'consul',
  'contingent account',
  'contingent liabilities',
  'contraband',
  'contracts',
  'conversation',
  'copy right',
  'corporate',
  'counterfoil',
  'credit',
  'credit balance',
  'credit note',
  'credit transactions',
  'cum dividend',
  'current account',
  'customs documents',
  'day book',
  'days of grace',
  'de facto holder',
  'dead of freight',
  'dealings',
  'debit balance',
  'debit note',
  'deferred shares',
  'defrayal',
  'defrayment',
  'defunct',
  'demurrage',
  'department of commerce',
  'depreciation',
  'designed',
  'differential',
  'discount',
  'distrait',
  'distribution',
  'dividend',
  'double entry system',
  'draft',
  'e commerce',
  'embargo',
  'endorsement',
  'enterprise',
  'entrepot',
  'entrepot trade',
  'ex dividend',
  'exchange',
  'export',
  'exportation',
  'exporting',
  'f.p.a',
  'faa',
  'fad',
  'fail',
  'finance',
  'fleets',
  'floating capital',
  'foreclosure',
  'forestry',
  'freight',
  'ftc',
  'gatt',
  'globalized',
  'gold standard',
  'goods',
  'goodwill',
  'government',
  'gross profit',
  'hermes',
  'hypothecation',
  'icc',
  'impersonal accounts',
  'imprest system',
  'indemnity',
  'industry',
  'insolvent',
  'instrument',
  'insurance',
  'interchange',
  'intercourse',
  'internet',
  'interstate',
  'investments',
  'invoice',
  'jettison',
  'joint stock company',
  'journal',
  'keelage',
  'lease',
  'ledger',
  'letter of credit',
  'liabilities',
  'limited company',
  'liquidation',
  'livelihood',
  'manpower',
  'manufacture',
  'mari',
  'maturity',
  'memorandum',
  'mercantilism',
  'merchandise',
  'merger',
  'minute book',
  'negotiable documents',
  'net cash',
  'net profit',
  'networking',
  'noaa',
  'outstanding expenses',
  'paid up capital',
  'par',
  'partnership',
  'pass book',
  'paying',
  'payment',
  'per pro',
  'petty cash book',
  'pledge',
  'possessions',
  'preference share',
  'premium',
  'prepaid',
  'price',
  'probate of will',
  'profit and loss account',
  'promissory note',
  'proxy',
  'quid proquo',
  'rate of discount',
  'rate of exchange',
  'registered capital',
  'reserved capital',
  'revenue',
  'securities',
  'sell',
  'seller',
  'shipbuilding',
  'shippers',
  'shipping',
  'single entry',
  'sold',
  'speculation',
  'statement of account',
  'statutory income',
  'stock in trade',
  'stock taking',
  'subscribed capital',
  'sundries',
  'surrender value',
  'suspense account',
  'tare',
  'tariff',
  'technology',
  'territory',
  'tinware',
  'trade',
  'trade balance',
  'trade discount',
  'traders',
  'trading',
  'traffic',
  'transport',
  'transportation',
  'tret',
  'trial balance',
  'truck',
  'ullage',
  'under writer',
  'usance',
  'value',
  'vendor',
  'voucher',
  'waiver',
  'ware',
  'warranty',
  'wasting assets',
  'wear and tear',
  'working capital',
  'working partner',
  'write off',
  'wto',
  'zickri chits'
]

export default (data) => {
  return pluralize(words);
}
