let words = [
  'bye',
  'goodbye',
  'good bye',
  'see you',
  'see ya',
  'cya',
  'farewell',
  'have a good day',
  'have a good one',
  'take care',
  'later',
  'see you later',
  'talk to you later',
  'all right then',
  'catch you later',
  'peace out',
  'smell you later',
  'i\'m out',
  'arrivederci',
  'adios',
  'au revoir',
  'sayonara',
  'goodnight',
  'unhello',
  'mcgoodbye',
  'cheerio',
  'so long',
  'bon voyage',
  'be well',
  'hasta la vista',
  'fare thee well',
  'later days',
  'that is all',
  'I\'m leaving now',
  'in a while crocodile',
  'cheers',
  'À voir',
  'À bientôt',
  'hasta la pasta',
  'abraço'
]

export default (data) => {
  return words.join('|');
}
