import pluralize from '../helpers/pluralize';

let words = [
  'Afghan hound',
  'African wild dog',
  'airedale terrier',
  'akita',
  'Alaskan malamute',
  'American cocker spaniel',
  'Australian cattle dog',
  'bark',
  'basenji',
  'basset hound',
  'beagle',
  'bergamasco',
  'bichon frise',
  'bird dog',
  'bloodhound',
  'border collie',
  'borzoi',
  'Boston terrier',
  'boxer',
  'breed',
  'briard',
  'Brittany',
  'bulldog',
  'bullmastiff',
  'bull terrier',
  'cairn terrier',
  'Cape hunting dog',
  'chihuahua',
  'Chinese crested dog',
  'chow chow',
  'cocker spaniel',
  'collie',
  'companion dog',
  'coon hound',
  'corgi',
  'cur',
  'dachshund',
  'Dalmatian',
  'dhole',
  'dingo',
  'Doberman pinscher',
  'dog',
  'elkhound',
  'feist',
  'fighting dog',
  'fox hound',
  'fox terrier',
  'German shepherd',
  'golden retriever',
  'great Dane',
  'great Pyrenees',
  'greyhound',
  'growl',
  'guard dog',
  'gun dogs',
  'harrier',
  'herding dog',
  'hound',
  'hunting dog',
  'husky',
  'Irish setter',
  'Jack Russell terrier',
  'keeshond',
  'kerry blue terrier',
  'King Charles spaniel',
  'Labrador retriever',
  'lap dog',
  'Lhasa apso',
  'malamute',
  'Maltese',
  'mastiff',
  'Mexican hairless',
  'miniature schnauser',
  'mongrel',
  'mutt',
  'Newfoundland',
  'Norfolk terrier',
  'old English sheepdog',
  'papillon',
  'pedigree',
  'pekingese',
  'pinscher',
  'pit bull',
  'pointer',
  'police dog',
  'pomeranian',
  'poodle',
  'Portuguese water dog',
  'pug',
  'pup',
  'puppy',
  'purebred',
  'rat terrier',
  'rescue dog',
  'retriever',
  'Rhodesian ridgeback',
  'rottweiler',
  'Saluki',
  'samoyed',
  'scent hound',
  'schnauser',
  'Scottish terrier',
  'search and rescue dog',
  'sled dog',
  'service dog',
  'setter',
  'Siberian husky',
  'sighthound',
  'spaniel',
  'spitz',
  'springer spaniel',
  'St. Bernard',
  'terrier',
  'toy dog',
  'utonagen',
  'vizsla',
  'water dog',
  'weimaraner',
  'Welsh corgi',
  'west highland white terrier',
  'westie',
  'wheaten terrier',
  'whippet',
  'wild dog',
  'working dog',
  'Yorkshire terrier'
];

export default (data) => {
  return pluralize(words);
}
