import pluralize from '../helpers/pluralize';

let words = [
  'air mask',
  'air tank',
  'alarm',
  'arson',
  'ashes',
  'ax',
  'axe',
  'backfire',
  'barricade',
  'blackened',
  'blaze',
  'boots',
  'bravery',
  'burn',
  'bystander',
  'captain',
  'catastrophe',
  'chain reaction',
  'char',
  'conflagration',
  'courage',
  'coveralls',
  'crackle',
  'crawl',
  'emergency',
  'engulf',
  'escape',
  'escape route',
  'explosion',
  'explosive',
  'extinguish',
  'extinguisher',
  'fire',
  'fire alarm',
  'fire engine',
  'fire drill',
  'fire extinguisher',
  'firefighter',
  'fire hook',
  'firehouse',
  'fire hydrant',
  'fireproof',
  'fire station',
  'firestorm',
  'fire truck',
  'flame',
  'flashlight',
  'flashpoint',
  'gas detector',
  'harm',
  'harness',
  'hazard',
  'haze',
  'heat',
  'helmet',
  'help',
  'hero',
  'heroic',
  'hose',
  'hydrant',
  'ignite',
  'ignition',
  'incendiary',
  'inferno',
  'inflammable',
  'inhalation',
  'jack, hydraulic',
  'jumpsuit',
  'kindling',
  'ladder truck',
  'matches',
  'nozzle',
  'panic',
  'peril',
  'plumes',
  'pole',
  'pump',
  'pumper truck',
  'pyromania',
  'rescue',
  'smoke',
  'smoke alarm',
  'smoke detector',
  'sparks',
  'sprinkler',
  'sprinkler system',
  'survival',
  'survive',
  'survivor',
  'suspenders',
  'tanker truck',
  'turnout jacket',
  'turnout pants'
];

export default (data) => {
  return pluralize(words);
}
