export default (data) => {
  [
    'hello',
    'hi',
    'hey',
    'hola',
    'howdy',
    'good morning',
    'good evening',
    'good afternoon',
    'morning',
    'what[^ ]* up',
    'sup',
    'how are you',
    'ciao',
    'how\'s it going',
    'well hello',
    'why hello there',
    'yo',
    'greetings',
    'look who it is',
    'look what the cat dragged in',
    'it\'s nice to meet you',
    'what\'s new',
    'g\'day',
    'what\'s happening',
    'what\'s happenin',
    'ello',
    'hiya',
    'haiiii',
    'aloha',
    'whuddup',
    'hullo',
    'ahoy',
    'how you doin',
    'que pasa',
    'bonjour',
    'hallo',
    'konnichiwa',
    'what have you been up to',
    'how are ya',
    'what’s crackin'
  ].join('|');
};
