let words = [
  'adore',
  'affable',
  'aggreeable',
  'amiable',
  'amused',
  'amusing',
  'animated',
  'appealing',
  'as happy as a clam',
  'beaming',
  'beatific',
  'beautiful',
  'bliss',
  'blissful',
  'blithe',
  'bowl over',
  'buoyant',
  'carefree',
  'charming',
  'cheerful',
  'cheeriness',
  'cheery',
  'chipper',
  'chirpy',
  'content',
  'contented',
  'delight',
  'delighted',
  'delightful',
  'diverting',
  'droll',
  'ebullient',
  'ecstasy',
  'ecstatic',
  'elated',
  'elation',
  'enchanting',
  'endearing',
  'energized',
  'engaging',
  'enjoyable',
  'enraptured',
  'entertaining',
  'euphoria',
  'euphoric',
  'euphoric',
  'excited',
  'exhilarated',
  'exuberance',
  'exultant',
  'exultation',
  'favorable',
  'fine',
  'friendly',
  'fulfilled',
  'fun',
  'funny',
  'genial',
  'get a kick out of',
  'glad',
  'gladden',
  'glee',
  'gleeful',
  'glorious',
  'glory',
  'glory in',
  'good',
  'good humored',
  'good mood',
  'good natured',
  'grateful',
  'gratified',
  'gratify',
  'gratifying',
  'great',
  'grinning',
  'happiness',
  'happy',
  'happy as a clam',
  'heartening',
  'heartwarming',
  'heavenly',
  'high',
  'high spirits',
  'hilarious',
  'hopeful',
  'in a good mood',
  'in good spirits',
  'in seventh heaven',
  'invigorated',
  'jocular',
  'joie de vivre',
  'jollity',
  'jolly',
  'jovial',
  'joy',
  'joyful',
  'joyfulness',
  'joyous',
  'jubilant',
  'jubilation',
  'jumping for joy',
  'lap up',
  'lighthearted',
  'likable',
  'looking on the bright side',
  'lovable',
  'lovely',
  'lucky',
  'luxuriate in',
  'merriment',
  'merry',
  'mirth',
  'mirthful',
  'mirthful',
  'never been better',
  'nice',
  'obliging',
  'on cloud nine',
  'on top of the world',
  'open',
  'opportune',
  'optomistic',
  'over the moon',
  'overjoyed',
  'paradise',
  'perkiness',
  'perky',
  'pleasant',
  'please greatly',
  'pleased',
  'pleasure',
  'precious',
  'radiant',
  'rapture',
  'rapturous',
  'relaxed',
  'relish',
  'revel in',
  'satisfied',
  'savor',
  'seventh heaven',
  'simpatico',
  'smiling',
  'source of pleasure',
  'sparkle',
  'stimulated',
  'sunniness',
  'sunny',
  'sweet',
  'take pleasure in',
  'tears of joy',
  'thrill',
  'thrilled',
  'tickled pink',
  'touching',
  'treat',
  'triumph',
  'untroubled',
  'upbeat',
  'uplifting',
  'vitalized',
  'vivacity',
  'walking on air',
  'welcoming',
  'willing',
  'wondrous',
  'zest for life'
];

export default (data) => {
  return words.join('|');
}
