import pluralize from '../helpers/pluralize';

let words = [
  'A frame',
  'BBQ grill',
  'CD player',
  'GPS',
  'MP3 player',
  'TV',
  'VCR',
  'Venetian blinds',
  'abode',
  'adobe house',
  'air conditioner',
  'alarm clock',
  'answering machine',
  'apartment',
  'appliances',
  'attached house',
  'attic',
  'awning',
  'back door',
  'backyard',
  'baluster',
  'barbecue',
  'barbecue grill',
  'barracks',
  'baseboard',
  'basement',
  'bathroom',
  'bathtub',
  'beach house',
  'beam',
  'bedroom',
  'blender',
  'blinds',
  'blowdryer',
  'boarding house',
  'broom',
  'brownstone',
  'building',
  'bungalow',
  'bunk bed',
  'bunkhouse',
  'burglar alarm',
  'cabin',
  'calculator',
  'camera',
  'can opener',
  'caravan',
  'carpet',
  'carport',
  'castle',
  'ceiling',
  'ceiling fan',
  'cell phone',
  'cellar',
  'chalet',
  'chateau',
  'chimney',
  'clock',
  'closet',
  'clothes dryer',
  'clothes washer',
  'co op',
  'coffee grinder',
  'coffee maker',
  'column',
  'computer',
  'concrete',
  'condo',
  'condominium',
  'convection oven',
  'copier',
  'cornice',
  'cottage',
  'counter',
  'country house',
  'crib',
  'crock pot',
  'cupboard',
  'curling iron',
  'curtain rod',
  'curtains',
  'dacha',
  'detached house',
  'dining room',
  'dish washer',
  'dishwasher',
  'doggie door',
  'doghouse',
  'domicile',
  'door',
  'door bell',
  'door jamb',
  'doorbell',
  'doorknob',
  'doorway',
  'dorm',
  'dormer',
  'dormitory',
  'double wide',
  'downspout',
  'downstairs',
  'drain',
  'drapes',
  'driveway',
  'dryer',
  'duct',
  'duplex',
  'dustpan',
  'dwelling',
  'earth sheltered house',
  'eaves',
  'edger',
  'efficiency apartment',
  'electric blanket',
  'electric drill',
  'electric fan',
  'electric guitar',
  'electric keyboard',
  'electric pencil sharpener',
  'electric razor',
  'electric toothbrush',
  'electrical outlet',
  'electrical system',
  'entrance',
  'entry',
  'entryway',
  'espresso maker',
  'estate',
  'family room',
  'fan',
  'farmhouse',
  'faucet',
  'fax machine',
  'fence',
  'fenced yard',
  'fire alarm',
  'fire extinguisher',
  'fireplace',
  'flashlight',
  'flat',
  'flatscreen TV',
  'floor',
  'food processor',
  'foundation',
  'frame',
  'freezer',
  'front door',
  'front stoop',
  'furnace',
  'furniture',
  'fuse box',
  'gable',
  'gabled house',
  'garage',
  'garage door',
  'garage door opener',
  'garbage can',
  'garbage disposal',
  'garden',
  'garden shed',
  'gate',
  'girder',
  'greenhouse',
  'grill',
  'guest house',
  'gutters',
  'hacienda',
  'hair clippers',
  'hair dryer',
  'hall',
  'hall closet',
  'hallway',
  'hamper',
  'headphones',
  'heater',
  'high rise home',
  'hinge',
  'home',
  'hood',
  'hose',
  'hot plate',
  'hotel',
  'house',
  'house trailer',
  'houseboat',
  'household',
  'housing project',
  'humidifier',
  'hunting lodge',
  'hut',
  'ice cream maker',
  'igloo',
  'inglenook',
  'inn',
  'insulation',
  'iron',
  'jamb',
  'juice',
  'kerosene heater',
  'key',
  'kitchen',
  'ladder',
  'lamp',
  'lanai',
  'lantern',
  'laptop',
  'laundry',
  'laundry room',
  'lawn mower',
  'lawnmower',
  'leaf blower',
  'lean to',
  'library',
  'light',
  'light switch',
  'linen closet',
  'lintel',
  'living quarters',
  'living room',
  'lock',
  'lodge',
  'lodging',
  'loft',
  'log cabin',
  'longhouse',
  'lumber',
  'mailbox',
  'maisonette',
  'manor',
  'mansion',
  'mantle',
  'mat',
  'microapartment',
  'microwave oven',
  'mirror',
  'mixer',
  'mobile home',
  'mop',
  'motel',
  'mousetrap',
  'newel',
  'nook',
  'nursery',
  'oven',
  'overhang',
  'painting',
  'palace',
  'paneling',
  'pantry',
  'patio',
  'penthouse',
  'percolator',
  'picture',
  'picture frame',
  'pied á terre',
  'plumbing',
  'pool',
  'porch',
  'portico',
  'pressure cooker',
  'primary residence',
  'printer',
  'pup tent',
  'quarters',
  'quilt',
  'radio',
  'railing',
  'rake',
  'ranch house',
  'range',
  'real estate',
  'record player',
  'recreation room',
  'refrigerator',
  'residence',
  'residential hall',
  'roof',
  'room',
  'rooming house',
  'rotisserie',
  'roundhouse',
  'row house',
  'rug',
  'saltbox',
  'sash',
  'scale',
  'scanner',
  'screen door',
  'sewing machine',
  'shack',
  'shed',
  'shelf',
  'shelter',
  'shelves',
  'shingle',
  'shower',
  'shutters',
  'siding',
  'sill',
  'sink',
  'skylight',
  'skyscraper',
  'sliding glass door',
  'smoke detector',
  'soffit',
  'split level house',
  'staircase',
  'stairs',
  'stairway',
  'stapler',
  'steps',
  'stereo',
  'stoop',
  'storage shed',
  'storm door',
  'stove',
  'studio apartment',
  'suite',
  'summer house',
  'swimming pool',
  'telephone',
  'television',
  'tenement',
  'tent',
  'tepee',
  'terraced house',
  'threshhold',
  'throw rug',
  'timer',
  'tipi',
  'toaster',
  'toaster oven',
  'toilet',
  'torch',
  'townhouse',
  'tract house',
  'trailer home',
  'trash can',
  'trash compactor',
  'treehouse',
  'trellis',
  'trim',
  'trimmer',
  'triplex',
  'tub',
  'tudor',
  'unit',
  'upstairs',
  'vacation house',
  'vacuum cleaner',
  'vaporizer',
  'vase',
  'vent',
  'video camera',
  'video game machine',
  'villa',
  'waffle iron',
  'wainscotting',
  'walkie talkie',
  'walkway',
  'wall',
  'wall to wall carpet',
  'washer',
  'washing machine',
  'waste basket',
  'watch',
  'water heater',
  'weather stripping',
  'welcome mat',
  'wickiup',
  'wigwam',
  'window',
  'window pane',
  'window sill',
  'wood stove',
  'yaodong',
  'yard',
  'yurt'
];

export default (data) => {
  return pluralize(words);
}
