import pluralize from '../helpers/pluralize';

let words = [
  'Abraham Lincoln',
  'America',
  'American',
  'American Revolution',
  'battles',
  'Bill of Rights',
  'birthday',
  'British',
  'celebrate',
  'cherry tree',
  'colonists',
  'Commander in Chief',
  'congress',
  'constitution',
  'Continental army',
  'Continental Congress',
  'democracy',
  'dentures',
  'elected',
  'election',
  'electoral college',
  'false teeth',
  'father of the country',
  'February',
  'federal holiday',
  'first president',
  'flag',
  'forefather',
  'general',
  'George Washington',
  'government',
  'history',
  'historic',
  'historical',
  'holiday',
  'leader',
  'leadership',
  'Liberty Bell',
  'Lincoln',
  'log cabin',
  'Martha Washington',
  'military',
  'Mount Vernon',
  'nation',
  'national',
  'New York City (early capital of the USA)',
  'oath of office',
  'patriot',
  'patriotism',
  'political',
  'political party',
  'politics',
  'president',
  'President\'s Day',
  'redcoats',
  'red, white and blue',
  'Revolution',
  'Revolutionary War',
  'seventeen seventy six (1776)',
  'Stars and Stripes',
  'states',
  'thirteen colonies',
  'unanimous election',
  'United States of America',
  'USA',
  'US Constitution',
  'vice president',
  'Virginia',
  'vote',
  'war',
  'Washington',
  'Washington, D. C. (current capital of the USA)',
  'White House'
];

export default (data) => {
  return pluralize(words);
}
