import pluralize from '../helpers/pluralize';

let words = [
  'bagpipe',
  'banshee',
  'blarney',
  'blarney stone',
  'bog',
  'brogue',
  'celebrate',
  'Celtic',
  'clover',
  'coins',
  'donnybrook',
  'Dublin',
  'emerald green',
  'Emerald Isle',
  'furtune',
  'four leaf clover',
  'Gaelic',
  'gold',
  'good luck',
  'green',
  'harp',
  'Hibernian',
  'holiday',
  'Ireland',
  'Irish',
  'Irish Republic',
  'jig',
  'legend',
  'leprechaun',
  'limerick',
  'little people',
  'luck',
  'luck of the Irish',
  'lucky',
  'magic',
  'magical',
  'March',
  'mischief',
  'mischievous',
  'Patrick',
  'patron',
  'potato',
  'pot of gold',
  'rainbow',
  'Republic of Ireland',
  'saint',
  'Saint Patrick',
  'seventeenth',
  'shillelagh',
  'shamrock',
  'snake',
  'St. Paddy\'s Day',
  'St. Patrick',
  'tradition',
  'Trifolium',
  'shamrock',
  'walking stick',
  'wearing of the green'
];

export default (data) => {
  return pluralize(words);
}
