'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _pluralize = require('./helpers/pluralize');

var _pluralize2 = _interopRequireDefault(_pluralize);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

let terms = [
  'amphibian',
  'amphiuma',
  'army of frogs',
  'barking frog',
  'black toad',
  'brook salamander',
  'bullfrog',
  'caecilian',
  'clawed frog',
  'climbing salamander',
  'common frog',
  'crested newt',
  'cricket frog',
  'disc tongued frog',
  'dusky salamander',
  'dwarf siren',
  'eastern newt',
  'ensatina',
  'European toad',
  'fire belly newt',
  'fire salamander',
  'fork tongued frog',
  'frog',
  'froglet',
  'Gerrothorax',
  'ghost frog',
  'giant salamander',
  'glass frog',
  'Goliath frog',
  'gold frog',
  'ground frog',
  'hellbender',
  'horned frog',
  'Indonesian floating frog',
  'Jefferson salamander',
  'knobby newt',
  'knot of toads',
  'leopard frog',
  'litter frog',
  'long toed salamander',
  'mantella frog',
  'Mexican treefrog',
  'moss frog',
  'mudpuppy',
  'mud salamander',
  'narrow mouthed frog',
  'natterjack',
  'newt',
  'ornate horned frog',
  'paddle tail newt',
  'painted frog',
  'poison arrow frog',
  'poison dart frog',
  'pollywog',
  'red legged frog',
  'red eft',
  'red eyed tree frog',
  'red salamander',
  'rice frog',
  'saddleback toad',
  'salamander',
  'sedge frog',
  'shovelnose frog',
  'siren',
  'spadefoot',
  'spotted newt',
  'spring peeper frog',
  'spring salamander',
  'tadpole',
  'tailed frog',
  'toad',
  'tongueless frog',
  'torrent salamander',
  'treefrog',
  'true frog',
  'true toad',
  'Vietnamese tree frog',
  'warty newt',
  'waterdog',
  'water frog',
  'western toad',
  'wood frog',
  'woodlands salamander',
  'yellow legged frog'
];

exports.default = (0, _pluralize2.default)(terms);
